Switch the close_firewall and kill_tunnels calls around
It's probably smarter to properly kill the tunnels before closing the
ports on them.  Don't want to make a mess.

diff --git a/vnc_tunnel b/vnc_tunnel
--- a/vnc_tunnel
+++ b/vnc_tunnel
@@ -114,18 +114,19 @@ function print_fail() {
 
 function cleanup() {
 	local dead=$1
-	printf "\nClosing VNC ports... "
-	if ! close_firewall; then
-		print_fail
-		echo "Failed to close ports.  Not fatal, but should be checked out."
-	else
-		print_ok
-	fi
 
 	printf "Killing SSH tunnel processes... "
 	if ! kill_tunnels; then
 		print_fail
 		echo "Failed to kill the tunnels.  Not fatal, but you might want to reboot"
+	else
+		print_ok
+	fi
+
+	printf "\nClosing VNC ports... "
+	if ! close_firewall; then
+		print_fail
+		echo "Failed to close ports.  Not fatal, but should be checked out."
 	else
 		print_ok
 	fi
