Add ping check and do some minor cleanup
It helps to check to make sure the provided IP responds to a ping
before trying to set up the tunnels.

diff --git a/vnc_tunnel b/vnc_tunnel
--- a/vnc_tunnel
+++ b/vnc_tunnel
@@ -82,6 +82,9 @@ function fix_hosts() {
 	local ip=$1
 	if ! grep -q "$ip.*spectre" /etc/hosts; then
 		sudo sed -i "s/.*spectre/$ip\tspectre/" /etc/hosts
+		printf " fixed "
+	else
+		printf " nothing to do "
 	fi
 	return $?
 }
@@ -148,11 +151,20 @@ if [[ $SKIP_HOSTS != 1 ]]; then
 	while ! echo $IP | grep -qEo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'; do
 		printf "Enter IP Address: "
 		read IP
+
+		if ! ping -c 1 $IP > /dev/null; then
+			echo "This IP is not responding to a ping.  Exiting."
+			cleanup dead
+		fi
 	done
 
 	printf "Fixing /etc/hosts file..."
-	if ! fix_hosts; then
-		fix_hosts $IP
+	if ! fix_hosts $IP; then
+		print_fail
+		echo "Failed to update /etc/hosts. Exiting"
+		cleanup dead
+	else
+		print_ok
 	fi
 else
 	echo "Skipping /etc/hosts update..."
